### ISSUE TITLE
How can be shown conditionally based on shipping zone?

### ISSUE THREAD

**Issue by sattip** [mypreview/woo-additional-terms#1]

**Comment by mahdiyazdani** [comment]
Well, at first glance it will need a custom options panel tab in WooCommerce settings.
We need to retrieve all submitted and valid shipping zones and display them with a repeater controller (I believe it is the best option for this use case)
Adding conditional logic based on country selection and shipping zones is not complicated since WooCommerce provides tons of hooks and filters for checkout template files it can be done with doing some customization and a little bit of JS.

When/if I release this feature I'll get back to you, I promise.
